PRN221_Assignment2/Pages/Cart/Index.cshtml.cs
using Bussiness.DTO;
using Bussiness.IRepository;
using Bussiness;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Http;
using Bussiness.Repository;
using Microsoft.AspNetCore.SignalR;
using PRN221_Assignment2.Hubs;

namespace PRN221_Assignment2.Pages.Cart
{
    public class IndexModel : PageModel
    {
        public List<CategoryDTO>? Categories { get; set; }
        private ICategoryRepository _categoryRepository;
        private IProductRepository _productRepository;

        public List<CartItem> Cart { get; set; }
        private IHubContext<SignalRServer> _signalRHub;

        public IndexModel(IHubContext<SignalRServer> hub, ICategoryRepository categoryRepository, IProductRepository productRepository)
        {
            _categoryRepository = categoryRepository;
            _productRepository = productRepository;
            _signalRHub = hub;
        }

        public void OnGet()
        {
            Cart = GetCartFromCookie();
            UpdateProductsInfo();
            Categories = _categoryRepository.GetCategories();
        }

        public IActionResult OnPostRemove(int productId)
        {
            List<CartItem> cart = GetCartFromCookie();
            CartItem? item = cart.FirstOrDefault(p => p.Product.ProductId == productId);
            if (item != null)
            {
                cart.Remove(item);
                TempData["success"] = "Xóa khỏi giỏ hàng thành công!";
                AddToCookie(cart);
            }
            return RedirectToPage("/Cart/Index");
        }

        public IActionResult OnPostUpdate(int productId, int amount)
        {
            Categories = _categoryRepository.GetCategories();
            List<CartItem> cart = GetCartFromCookie();
            CartItem? item = cart.FirstOrDefault(p => p.Product.ProductId == productId);
            if (item != null)
            {
                if (item.Quantity + amount == 0)
                {
                    cart.Remove(item);
                    TempData["success"] = "Đã xóa ra khỏi giỏ hàng";
                }
                else if (item.Quantity + amount <= item.Product.UnitsInStock)
                {
                    item.Quantity += amount;
                    TempData["success"] = "Cập nhật thành công";
                }
                else
                {
                    TempData["error"] = "Đã hết số lượng trong kho";
                }
                item.Product.Category = null;
            }
            await _signalRHub.Clients.All.SendAsync("buy");
            AddToCookie(cart);
            return RedirectToPage("/Cart/Index");
        }

        private void AddToCookie(List<CartItem> cart)
        {
            // config to skip property that cause infinite loop
            JsonSerializerSettings settings = new JsonSerializerSettings
            {
                ReferenceLoopHandling = ReferenceLoopHandling.Ignore
            };

            // Convert from object to Json
            string updatedCartJson = JsonConvert.SerializeObject(cart, settings);
            CookieOptions options = new CookieOptions
            {
                // only access by http or https, not Javascript
                HttpOnly = true,
                Expires = DateTime.Now.AddDays(7)
            };
            Response.Cookies.Append("cart", updatedCartJson, options);
        }

        private List<CartItem> GetCartFromCookie()
        {
            string cartJson = Request?.Cookies["cart"];
            if (cartJson != null)
            {
                // Convert from Json to object
                return JsonConvert.DeserializeObject<List<CartItem>>(cartJson);
            }
            else
            {
                return new List<CartItem>();
            }
        }

        private void UpdateProductsInfo()
        {
            Cart.ForEach(c =>
            {
                ProductDTO? product = _productRepository.GetProduct(c.Product.ProductId);
                //UPDATE PRODUCT 
                product.Category.Picture = null;
                product.Category.Products = null;
                c.Product = product;
            });
            AddToCookie(Cart);
        }

        public IActionResult OnGetUpdateCartListComp()
        {
            return ViewComponent("CartList");
        }
    }
}

PRN221_Assignment2/Pages/Cart/Process.cshtml.cs
using Bussiness.DTO;
using Bussiness.IRepository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.SignalR;
using Newtonsoft.Json;
using PRN221_Assignment2.Extensions;
using PRN221_Assignment2.Hubs;

namespace PRN221_Assignment2.Pages.Cart
{
    public class ProcessModel : PageModel
    {
        public List<CategoryDTO>? Categories { get; set; }
        private ICategoryRepository _categoryRepository;
        private IOrderRepository _orderRepository;
        private IProductRepository _productRepository;
        private IOrderDetailRepository _orderDetailRepository;

        public List<CartItem> Cart { get; set; }
        public List<CartItem> PurchaseCart { get; set; }

        private IHubContext<SignalRServer> _signalRHub;

        public ProcessModel(IHubContext<SignalRServer> hub ,ICategoryRepository categoryRepository, IOrderDetailRepository orderDetailRepository, IOrderRepository orderRepository, IProductRepository productRepository)
        {
            _categoryRepository = categoryRepository;
            _orderDetailRepository = orderDetailRepository;
            _orderRepository = orderRepository;
            _productRepository = productRepository;
            _signalRHub = hub;
        }

        public IActionResult OnGet(int[] purchase_product)
        {
            Cart = GetCartFromCookie();
            if(Cart.Count == 0 || purchase_product.Length == 0)
            {
                TempData["error"] = "Vui lòng chọn sản phẩm trước khi đặt hàng!";
                return RedirectToPage("/Cart/Index");
            }

            PurchaseCart = GetPurchaseCart(purchase_product);
            HttpContext.Session.Set<List<CartItem>>("cart_product_list", PurchaseCart);
            Categories = _categoryRepository.GetCategories();
            return Page();
        }

        private List<CartItem> GetPurchaseCart(int[] purchase_product)
        {
            List<CartItem> cart = new List<CartItem>();
            for (int i = 0; i < purchase_product.Length; i++)
            {
                CartItem? item = Cart.FirstOrDefault(c => c.Product.ProductId == purchase_product[i]);
                if (item != null)
                {
                    cart.Add(item);
                }
            }
            return cart;
        }

        private List<CartItem> GetCartFromCookie()
        {
            string cartJson = Request?.Cookies["cart"];
            if (cartJson != null)
            {
                // Convert from Json to object
                return JsonConvert.DeserializeObject<List<CartItem>>(cartJson);
            }
            else
            {
                return new List<CartItem>();
            }
        }

        public async Task<IActionResult> OnPost(string? fullname, string? email, string? phoneNumber, string? address, string? city, string? district, string? ward, string? paymentMedthod)
        {
            Cart = GetCartFromCookie();
            PurchaseCart =  HttpContext.Session.Get<List<CartItem>>("cart_product_list");
            if (PurchaseCart.Count > 0)
            {
                //Check if product is availble
                if (!CheckAvailbleProduct())
                {
                    TempData["error"] = "Đặt hàng thất bại!";
                    return RedirectToPage("/Cart/Index");
                }

                OrderDTO order = new()
                {
                    ShipCountry = "VietNam",
                    ShipCity = city,
                    ShipRegion = district,
                    ShipAddress = address + ", " + ward,
                    ShipName = fullname,
                    OrderDate = DateTime.Now,
                    ShipVia = paymentMedthod.Equals("cod") ? 1 : 0,
                    Email = email,
                    PhoneNumber = phoneNumber
                };

                if (!_orderRepository.AddOrder(order))
                {
                    TempData["error"] = "Đặt hàng thất bại!";
                    return RedirectToPage("/Cart/Index");
                }

                int orderId = _orderRepository.GetLastInsertOrderId();
                AddOrderDetail(orderId);

                TempData["success"] = "Đặt hàng thành công!";
                UpdateCookie(PurchaseCart);

                await _signalRHub.Clients.All.SendAsync("buy");
                return RedirectToPage("/Cart/Success", new { code = orderId });
            }
            TempData["error"] = "Đặt hàng thất bại!";
            return RedirectToPage("/Cart/Index");
        }

        private void AddOrderDetail(int orderId)
        {
            PurchaseCart.ForEach(c =>
            {
                _orderDetailRepository.Add(
                new OrderDetailDTO
                {
                    OrderId = orderId,
                    UnitPrice = (decimal)c.Product.PromotionPrice,
                    ProductId = c.Product.ProductId,
                    Quantity = (short)c.Quantity
                });

                _productRepository.UpdateUnitInStock(c.Product, c.Quantity);
            });
        }

        private void UpdateCookie(List<CartItem> buyCart)
        {
            for (int i = 0; i < Cart.Count; i++)
            {
                for (int j = 0; j < buyCart.Count; j++)
                {
                    if (Cart[i].Product.ProductId == buyCart[j].Product.ProductId)
                    {
                        Cart.Remove(Cart[i]);
                    }
                }
            }

            AddToCookie(Cart);
        }

        bool CheckAvailbleProduct()
        {
            foreach (var cartItem in PurchaseCart)
            {
                ProductDTO? product = _productRepository.GetProduct(cartItem.Product.ProductId);
                if (product == null || product.UnitsInStock < cartItem.Quantity)
                {
                    return false;
                }
            }
            return true;
        }

        private void AddToCookie(List<CartItem> cart)
        {
            // config to skip property that cause infinite loop
            JsonSerializerSettings settings = new JsonSerializerSettings
            {
                ReferenceLoopHandling = ReferenceLoopHandling.Ignore
            };

            // Convert from object to Json
            string updatedCartJson = JsonConvert.SerializeObject(cart, settings);
            CookieOptions options = new CookieOptions
            {
                // only access by http or https, not Javascript
                HttpOnly = true,
                Expires = DateTime.Now.AddDays(7)
            };
            Response.Cookies.Append("cart", updatedCartJson, options);
        }
    }
}

PRN221_Assignment2/Pages/Cart/Success.cshtml.cs
using Bussiness.DTO;
using Bussiness.IRepository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace PRN221_Assignment2.Pages.Cart
{
    public class SuccessModel : PageModel
    {
        private ICategoryRepository _categoryRepository;
        public List<CategoryDTO>? Categories { get; set; }

        public SuccessModel(ICategoryRepository categoryRepository)
        {
            _categoryRepository = categoryRepository;
        }

        public void OnGet(int? code)
        {
            Categories = _categoryRepository.GetCategories();
            ViewData["OrderCode"] = code;
        }
    }
}

PRN221_Assignment2/Pages/Shared/Components/CartList/CartListViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Bussiness.DTO;
using Newtonsoft.Json;

namespace PRN221_Assignment2.Pages.Shared.Components.CartList
{
    public class CartListViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var cart = GetCartFromCookie();
            return View(cart);
        }

        private List<CartItem> GetCartFromCookie()
        {
            string cartJson = Request.Cookies["cart"];
            if (cartJson != null)
            {
                // Convert from Json to object
                return JsonConvert.DeserializeObject<List<CartItem>>(cartJson);
            }
            else
            {
                return new List<CartItem>();
            }
        }
    }
}

PRN221_Assignment2/Pages/Cart/Index.cshtml
@page "/cart"
@model PRN221_Assignment2.Pages.Cart.IndexModel

@{
    ViewData["Title"] = "Giỏ hàng";
}
<head>
    <title>Giỏ hàng</title>
    <link href="~/css/bootstrap.css" rel="stylesheet">
    <link href="~/css/ui.css" rel="stylesheet">
    <link href="~/css/responsive.css" rel="stylesheet">
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js" type="text/javascript"></script>
    <link type="text/css" rel="stylesheet" href="~/css/cart.css">
</head>

<style>
    a {
        text-decoration: none;
        color: black;
    }

    .header_menu li a {
        color: #6c6c6c;
    }
</style>

<!-- ========================= SECTION PAGETOP ========================= -->
<section class="section-pagetop bg">
    <div class="container">
        <h2 class="title-page mb-3">Giỏ hàng của bạn</h2>
    </div> <!-- container //  -->
</section>

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-content padding-y">
    <div class="container">
        <div class="row">
            <main class="col-md-9">
                <div class="card">
                    @if (Model.Cart != null && Model.Cart.Count > 0)
                    {
                        <table class="table table-borderless table-shopping-cart">
                            <thead class="text-muted">
                                <tr class="small text-uppercase">
                                    <th scope="col" style="margin-right: 10px;">
                                        <input type="checkbox" name="purchase_all_product" onclick="tickCheckbox(this)" form="purchase-button" value="0">
                                    </th>
                                    <th scope="col">Sản phẩm</th>
                                    <th scope="col" width="120">Giá tiền</th>
                                    <th scope="col" width="120">Số lượng</th>
                                    <th scope="col" width="120">Thành tiền</th>
                                    <th scope="col" class="text-right" width="200"></th>
                                </tr>
                            </thead>
                            <tbody id="cart-list-part">
                                @await Component.InvokeAsync("CartList")
                            </tbody>
                        </table>

                        <div class="card-body border-top">
                            <a asp-page="/Product/Shop" class="btn btn-primary float-md-right"> <i class="fa fa-chevron-left"></i> Tiếp tục mua hàng</a>
                        </div>
                    }
                    else
                    {
                        <h3 class="my-5 fw-normal">Bạn chưa có sản phẩm nào trong giỏ hàng</h3>
                        <div class="card-body border-top">
                            <a asp-page="/Product/Shop" class="btn btn-primary float-md-right"> <i class="fa fa-chevron-left"></i> Mua hàng ngay</a>
                        </div>
                    }
                </div> <!-- card.// -->

                <div class="alert alert-success mt-3">
                    <p class="icontext"><i class="icon text-success fa fa-truck"></i> Giao hàng trong vòng từ 1 - 3 ngày</p>
                </div>

            </main> <!-- col.// -->
            <aside class="col-md-3">
                <div class="card mb-3">
                    <div class="card-body">
                        <form>
                            <div class="form-group">
                                <label>Mã khuyến mãi</label>
                                <div class="input-group">
                                    <input type="text" class="form-control" name="" placeholder="Coupon code">
                                    <span class="input-group-append">
                                        <button class="btn btn-primary">Áp dụng</button>
                                    </span>
                                </div>
                            </div>
                        </form>
                    </div> <!-- card-body.// -->
                </div>  <!-- card .// -->
                <div class="card" id="order-calculation">
                    @*@await Component.InvokeAsync("CartBill")*@
                    <div class=" iRKLRb">
                        <ul class="prices__items">
                            <li class="prices__item">
                                <span class="prices__text">Tạm tính</span>
                                <span class="prices__value"><span class="buy-sum-money">0</span> $</span>
                            </li>
                            <li class="prices__item">
                                <span class="prices__text">Giảm giá</span>
                                <span class="prices__value">0 $</span>
                            </li>
                        </ul>
                        <div class="prices__total">
                            <span class="prices__text">Tổng tiền</span>
                            <div class="prices__content">
                                <span class="prices__value prices__value--final"><span class="buy-sum-money">0</span> $</span>
                                <span class="prices__value--noted">(Đã bao gồm VAT nếu có)</span>
                            </div>
                        </div>
                        <form id="purchase-button" asp-page="/Cart/Process" method="GET">
                            @if (Model?.Cart != null && Model.Cart.Count > 0)
                            {
                                <button class="bsEPkA" type="submit">Mua Hàng</button>
                            }
                            else
                            {
                                <button class="bsEPkA" disabled="">Mua Hàng</button>
                            }
                        </form>
                    </div> <!-- card-body.// -->
                </div>  <!-- card .// -->
            </aside> <!-- col.// -->
        </div>

    </div> <!-- container .//  -->
</section>

<!-- ========================= FOOTER ========================= -->
<script>

    function tickCheckbox(allcheck) {
        var checkboxes = document.getElementsByName('purchase_product');
        for (var checkbox of checkboxes) {
            if (allcheck.checked === true) {
                checkbox.checked = true;
            } else {
                checkbox.checked = false;
            }
        }
    }
    var checkboxList = document.getElementsByName('purchase_product');
    checkboxList.forEach(cb => {
        cb.addEventListener('change', event => {
            const total = recountTotalMoney(checkboxList);
            const totalText = document.querySelectorAll('.buy-sum-money');
            totalText[0].innerHTML = total;
            totalText[1].innerHTML = total;
        })
    });

    function recountTotalMoney(checkboxList) {
        let total = 0;
        checkboxList.forEach(cb => {
            if (cb.checked == true) {
                let priceItem = cb.parentElement.parentElement.parentElement.querySelector('.item-price-total').innerHTML;
                total += parseInt(priceItem);
            }
        });
        return total;
    }
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/microsoft-signalr/7.0.9/signalr.js"></script>

<script>
    var connection = new signalR.HubConnectionBuilder()
        .withUrl("/signalRHub")
        .build();

    connection.on("buy", function () {
        $('#cart-list-part').load("/cart?handler=UpdateCartListComp");
    });
    connection.start().catch(function (err) {
        console.error(err.toString());
    });
</script>

PRN221_Assignment2/Pages/Cart/Success.cshtml
@page "/order/success"

@model PRN221_Assignment2.Pages.Cart.SuccessModel
@{
    ViewData["Title"] = "Đặt hàng thành công";
}
<head>
    <link rel='stylesheet' type='text/css' media='screen' href='~/css/bootstrap.css'>
</head>
<style>

    .mess {
        color: #f01414;
    }

    .order-id span {
        display: inline-block;
        padding: 10px 50px;
        background: #15ad15;
        color: #fff;
        font-size: 20px;
    }

    .order-id {
        margin: 0 auto;
        width: fit-content;
    }

        .order-id p {
            font-weight: 600;
            margin: 0 auto;
            width: fit-content;
        }
</style>

<section class="section-pagetop bg">
    <div class="container">
        <div class="mess">
            <h3 class="my-5">Cảm ơn bạn đã mua hàng tại Hola Farm</h3>
        </div>

        <div class="order-id">
            <p>Mã số đơn hàng của bạn</p>
            <span>@ViewData["OrderCode"]</span>
        </div>

        <a class="my-3 text-center d-block" href="/orders/list">Xem đơn hàng</a>
    </div> <!-- container //  -->
</section>