PRN221_Assignment2/Pages/Cart/Index.cshtml.cs
using Bussiness.DTO;
using Bussiness.IRepository;
using Bussiness;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Http;
using Bussiness.Repository;
using Microsoft.AspNetCore.SignalR;
using PRN221_Assignment2.Hubs;

namespace PRN221_Assignment2.Pages.Cart
{
    public class IndexModel : PageModel
    {
        public List<CategoryDTO>? Categories { get; set; }
        private ICategoryRepository _categoryRepository;
        private IProductRepository _productRepository;

        public List<CartItem> Cart { get; set; }
        private IHubContext<SignalRServer> _signalRHub;

        public IndexModel(IHubContext<SignalRServer> hub, ICategoryRepository categoryRepository, IProductRepository productRepository)
        {
            _categoryRepository = categoryRepository;
            _productRepository = productRepository;
            _signalRHub = hub;
        }

        public void OnGet()
        {
            Cart = GetCartFromCookie();
            UpdateProductsInfo();
            Categories = _categoryRepository.GetCategories();
        }

        public IActionResult OnPostRemove(int productId)
        {
            List<CartItem> cart = GetCartFromCookie();
            CartItem? item = cart.FirstOrDefault(p => p.Product.ProductId == productId);
            if (item != null)
            {
                cart.Remove(item);
                TempData["success"] = "Xóa khỏi giỏ hàng thành công!";
                AddToCookie(cart);
            }
            return RedirectToPage("/Cart/Index");
        }

        public IActionResult OnPostUpdate(int productId, int amount)
        {
            Categories = _categoryRepository.GetCategories();
            List<CartItem> cart = GetCartFromCookie();
            CartItem? item = cart.FirstOrDefault(p => p.Product.ProductId == productId);
            if (item != null)
            {
                if (item.Quantity + amount == 0)
                {
                    cart.Remove(item);
                    TempData["success"] = "Đã xóa ra khỏi giỏ hàng";
                }
                else if (item.Quantity + amount <= item.Product.UnitsInStock)
                {
                    item.Quantity += amount;
                    TempData["success"] = "Cập nhật thành công";
                }
                else
                {
                    TempData["error"] = "Đã hết số lượng trong kho";
                }
                item.Product.Category = null;
            }
            await _signalRHub.Clients.All.SendAsync("buy");
            AddToCookie(cart);
            return RedirectToPage("/Cart/Index");
        }

        private void AddToCookie(List<CartItem> cart)
        {
            // config to skip property that cause infinite loop
            JsonSerializerSettings settings = new JsonSerializerSettings
            {
                ReferenceLoopHandling = ReferenceLoopHandling.Ignore
            };

            // Convert from object to Json
            string updatedCartJson = JsonConvert.SerializeObject(cart, settings);
            CookieOptions options = new CookieOptions
            {
                // only access by http or https, not Javascript
                HttpOnly = true,
                Expires = DateTime.Now.AddDays(7)
            };
            Response.Cookies.Append("cart", updatedCartJson, options);
        }

        private List<CartItem> GetCartFromCookie()
        {
            string cartJson = Request?.Cookies["cart"];
            if (cartJson != null)
            {
                // Convert from Json to object
                return JsonConvert.DeserializeObject<List<CartItem>>(cartJson);
            }
            else
            {
                return new List<CartItem>();
            }
        }

        private void UpdateProductsInfo()
        {
            Cart.ForEach(c =>
            {
                ProductDTO? product = _productRepository.GetProduct(c.Product.ProductId);
                //UPDATE PRODUCT 
                product.Category.Picture = null;
                product.Category.Products = null;
                c.Product = product;
            });
            AddToCookie(Cart);
        }

        public IActionResult OnGetUpdateCartListComp()
        {
            return ViewComponent("CartList");
        }
    }
}

PRN221_Assignment2/Pages/Shared/Components/CartBill/CartBillViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Bussiness.DTO;
using Newtonsoft.Json;

namespace PRN221_Assignment2.Pages.Shared.Components.CartBill
{
    public class CartBillComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var cart = GetCartFromCookie();
            return View(cart);
        }

        private List<CartItem> GetCartFromCookie()
        {
            string cartJson = Request.Cookies["cart"];
            if (cartJson != null)
            {
                // Convert from Json to object
                return JsonConvert.DeserializeObject<List<CartItem>>(cartJson);
            }
            else
            {
                return new List<CartItem>();
            }
        }
    }
}

PRN221_Assignment2/Pages/Shared/Components/CartList/CartListViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Bussiness.DTO;
using Newtonsoft.Json;

namespace PRN221_Assignment2.Pages.Shared.Components.CartList
{
    public class CartListViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var cart = GetCartFromCookie();
            return View(cart);
        }

        private List<CartItem> GetCartFromCookie()
        {
            string cartJson = Request.Cookies["cart"];
            if (cartJson != null)
            {
                // Convert from Json to object
                return JsonConvert.DeserializeObject<List<CartItem>>(cartJson);
            }
            else
            {
                return new List<CartItem>();
            }
        }
    }
}

PRN221_Assignment2/Pages/Shared/Components/CartNumber/CartNumberViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Bussiness.DTO;
using Newtonsoft.Json;

namespace PRN221_Assignment2.Pages.Shared.Components.CartNumber
{
    public class CartNumberViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var cart = GetCartFromCookie();
            return View(cart);
        }

        private List<CartItem> GetCartFromCookie()
        {
            string cartJson = Request.Cookies["cart"];
            if (cartJson != null)
            {
                // Convert from Json to object
                return JsonConvert.DeserializeObject<List<CartItem>>(cartJson);
            }
            else
            {
                return new List<CartItem>();
            }
        }
    }
}

PRN221_Assignment2/Pages/Shared/Components/CartList/Default.cshtml
@model List<CartItem>
@foreach (CartItem item in Model)
{
    <tr style="@item.Product.UnitsInStock @item.Quantity @(item.Product.UnitsInStock >= item.Quantity ? "": "opacity: 0.5;")">
        <td>
            <div class="buy-or-later">
                @if (item.Product.UnitsInStock <= 0 || item.Product.UnitsInStock < item.Quantity)
                {
                    <input type="checkbox" disabled form="purchase-button" name="purchase_product" value="@item.Product.ProductId">
                }
                else
                {
                    <input type="checkbox" form="purchase-button" name="purchase_product" value="@item.Product.ProductId">
                }
            </div>
        </td>
        <td>
            <div class="product-name-image">
                <img src="@(item.Product.ImgUrl)" class="img-sm" width="80" height="80">
                <p class="info">
                    <a asp-page="/Product/ProductDetail" asp-route-id="@item.Product.ProductId">@item.Product.ProductName</a>
                </p>
            </div>
        </td>
        <td>
            <div class="price-wrap">
                <span class="price">@(item.Product.PromotionPrice) $</span>
            </div> <!-- price-wrap .// -->
        </td>
        <td class="change-quantity">
            @if (item.Product.UnitsInStock > 0)
            {
                <form method="post" id="progress-order-form" asp-page="/Cart/Index" asp-page-handler="Update" >
                    <div class="content-box">
                        <span class="decrease-quantity-btn" >
                            <img src="https://frontend.tikicdn.com/_desktop-next/static/img/icons/decrease.svg" alt="decrease">
                        </span>
                        <span class="quantity-display">@item.Quantity</span>
                        <span class="increase increase-quantity-btn">
                            <img src="https://frontend.tikicdn.com/_desktop-next/static/img/icons/increase.svg" alt="increase"><!-- comment -->
                        </span>
                        <input type="hidden" name="productId" value="@item.Product.ProductId"/>
                        <input type="hidden" name="amount" value="0"/>
                    </div>
                </form>
            }
        </td>
        <td>
            @if (item.Product.UnitsInStock > 0)
            {
                <div class="total-price-wrap">
                    <span class="item-price-total">@(item.TotalMoney())</span> $
                </div> <!-- price-wrap .// -->
            }
        </td>
        <td class="text-right">
            <form method="post" asp-page="/Cart/Index" asp-page-handler="Remove" onsubmit="return confirm('Are you sure you want to delete this item?');">
                <input type="hidden" value="@item.Product.ProductId" name="productId" />
                <button type="submit" class="btn btn-light remove-item-button"><img src="https://frontend.tikicdn.com/_desktop-next/static/img/icons/trash.svg" alt="deleted"></button>
            </form>
        </td>
    </tr>

}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://code.jquery.com/jquery-2.2.0.min.js" type="text/javascript"></script>
@*<script>
    Array.from(document.querySelectorAll('.remove-item-button')).forEach(
        (btn) => {
            btn.addEventListener('click', function (e) {
                $.ajax({
                    url: '/api/cart/remove',
                    type: "POST",
                    data: {
                        productId: parseInt(e.currentTarget.value),
                    },
                    dataType: "JSON",
                    headers: {
                    RequestVerificationToken: 
                        $('input:hidden[name="__RequestVerificationToken"]').val()
                    },
                    success: function (result) {
                        if (result.success) {
                            $('#cart-header').load("/AjaxContent/NumberCart");
                            $('tbody').load("/AjaxContent/CartList");
                            $('#order-calculation').load("/AjaxContent/SumCart");
                        }
                    },
                    error: function (xhr) {
                        alert("Xóa sản phẩm không thành công");
                    }
                });
            });
        });
        });
</script>*@
<script type="text/javascript">
    Array.from(document.querySelectorAll('.decrease-quantity-btn')).forEach(
        (btn) => {
            btn.addEventListener('click', function (e) {
                btn.parentElement.querySelector('input[name="amount"]').value  = -1;
                btn.parentElement.parentElement.submit();
            });
        });

    Array.from(document.querySelectorAll('.increase-quantity-btn')).forEach(
        (btn) => {
            btn.addEventListener('click', function (e) {
                 btn.parentElement.querySelector('input[name="amount"]').value = 1;
                 btn.parentElement.parentElement.submit();
            });
    });
</script>